'use client'
import { useEffect, useState } from 'react'
import { supabase } from '../../lib/supabase'
import type { Listing } from '../../lib/types'

export default function StudentPage() {
  const [listings, setListings] = useState<Listing[]>([]); const [query, setQuery] = useState(''); const [city, setCity] = useState('Jaipur'); const [note, setNote] = useState(''); const [loading, setLoading] = useState(true)
  async function load() { setLoading(true); let request = supabase.from('tutor_listings').select('*').eq('status','active').order('created_at',{ascending:false}); if (city) request=request.ilike('city',`%${city}%`); const { data, error } = await request; setListings(error ? [] : data as Listing[]); setLoading(false) }
  useEffect(()=>{ load() },[])
  async function enquire(listing: Listing) { const { data: { user } } = await supabase.auth.getUser(); if (!user) { location.href='/auth'; return } const { error } = await supabase.from('enquiries').insert({ listing_id: listing.id, student_id: user.id, message: `Interested in a free demo for ${listing.title}.` }); setNote(error ? error.message : `Enquiry sent to ${listing.title}. They will contact you soon.`) }
  const visible = listings.filter(x => `${x.title} ${x.category} ${x.locality||''}`.toLowerCase().includes(query.toLowerCase()))
  return <main><section className="search-hero"><p className="eyebrow">FOR STUDENTS & PARENTS</p><h1>Find a class with confidence.</h1><p>Compare verified nearby tutors and coaching institutes, then request a free demo.</p><div className="search-bar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="What do you want to learn?" /><input value={city} onChange={e=>setCity(e.target.value)} placeholder="City or locality" /><button className="primary" onClick={load}>Find classes</button></div></section><section className="content"><aside className="filters"><b>Search tips</b><p>Use a subject, exam, class level, or locality.</p><hr/><b>Trust comes first</b><p>Only admin-approved listings appear here.</p></aside><div><div className="result-title"><div><p className="eyebrow">CLASSES NEAR YOU</p><h2>Recommended matches</h2></div><span>{visible.length} verified classes</span></div>{note && <p className="notice">{note}</p>}<div className="cards">{loading ? <p>Loading trusted classes…</p> : visible.length ? visible.map(x=><article className="listing" key={x.id}><div className="listing-cover">{x.category.slice(0,1)}</div><div className="listing-body"><span className="verified">✓ VERIFIED</span><h3>{x.title}</h3><p>{x.category} · {x.locality ? `${x.locality}, ` : ''}{x.city}</p><p className="description">{x.description || 'Contact this tutor to learn about batches and a free demo.'}</p><div className="listing-bottom"><b>{x.fee_from ? `From ₹${x.fee_from}/month` : 'Fees on enquiry'}</b><button onClick={()=>enquire(x)}>Get free demo →</button></div></div></article>) : <p>No active classes found in this city yet. Try another search or check back soon.</p>}</div></div></section></main>
}
