'use client'
import { FormEvent, useEffect, useState } from 'react'
import { supabase } from '../../../lib/supabase'

export default function NewListingPage() {
  const [message,setMessage]=useState(''); const [allowed,setAllowed]=useState<boolean|null>(null)
  useEffect(()=>{ supabase.auth.getUser().then(({data:{user}})=>{ if(!user) {location.href='/auth'; return} supabase.from('profiles').select('role').eq('id',user.id).single().then(({data})=>setAllowed(data?.role==='tutor'||data?.role==='admin')) }) },[])
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const {data:{user}}=await supabase.auth.getUser(); if(!user) return; const f=new FormData(e.currentTarget); const row={ owner_id:user.id,title:String(f.get('title')),category:String(f.get('category')),city:String(f.get('city')),locality:String(f.get('locality'))||null,fee_from:Number(f.get('fee_from'))||null,fee_to:Number(f.get('fee_to'))||null,modes:[String(f.get('mode'))],description:String(f.get('description')) }; const {error}=await supabase.from('tutor_listings').insert(row); setMessage(error?error.message:'Your listing was submitted. It will appear publicly after admin verification.'); if(!error)e.currentTarget.reset() }
  if(allowed===null)return <main className="form-page">Checking your account…</main>; if(!allowed)return <main className="form-page"><h1>Use a tutor account to list classes.</h1><p>Create a new Tutor / Institute account from the signup page.</p><a className="primary inline" href="/auth">Create tutor account</a></main>
  return <main className="form-page"><div className="form-copy"><p className="eyebrow">FOR TUTORS & INSTITUTES</p><h1>Tell students about your classes.</h1><p>A clear profile makes it easier for the right family to enquire. Your listing is reviewed before it goes live.</p><ul><li>No setup fee</li><li>You control your own batches and fees</li><li>Receive enquiries in one dashboard</li></ul></div><form className="form-card" onSubmit={submit}><p className="eyebrow">CREATE FREE LISTING</p><h2>Your teaching profile</h2><label>Institute or tutor name<input required name="title" placeholder="e.g. Bright Minds Academy" /></label><div className="two"><label>City<input required name="city" placeholder="e.g. Jaipur" /></label><label>Locality<input name="locality" placeholder="e.g. Vaishali Nagar" /></label></div><label>Primary category<select required name="category"><option value="">Choose a category</option><option>School tuition</option><option>Competitive exams</option><option>Languages</option><option>Computer & skills</option></select></label><div className="two"><label>Fees from (monthly)<input name="fee_from" type="number" min="0" placeholder="1500" /></label><label>Fees to (monthly)<input name="fee_to" type="number" min="0" placeholder="3000" /></label></div><label>Teaching mode<select name="mode"><option>At institute</option><option>Home tuition</option><option>Online</option><option>Hybrid</option></select></label><label>Short description<textarea name="description" required placeholder="Mention subjects, class levels, batches and what makes your teaching helpful." /></label><button className="primary">Submit for verification</button>{message&&<p className="notice">{message}</p>}</form></main>
}
