'use client'
import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import { supabase } from '../../../lib/supabase'
import type { Listing, Review } from '../../../lib/types'

export default function TutorProfilePage(){
  const params = useParams(); const id = params?.id as string
  const [listing,setListing]=useState<Listing|null>(null); const [reviews,setReviews]=useState<Review[]>([]); const [loading,setLoading]=useState(true); const [note,setNote]=useState(''); const [myRating,setMyRating]=useState(0); const [comment,setComment]=useState(''); const [isStudent,setIsStudent]=useState(false)
  async function loadReviews(){ const {data} = await supabase.from('reviews').select('*').eq('listing_id',id).order('created_at',{ascending:false}); setReviews((data as Review[])||[]) }
  useEffect(()=>{(async()=>{ const {data} = await supabase.from('tutor_listings').select('*').eq('id',id).eq('status','active').single(); setListing(data as Listing); await loadReviews(); const {data:{user}} = await supabase.auth.getUser(); if(user){ const {data:p} = await supabase.from('profiles').select('role').eq('id',user.id).single(); setIsStudent(p?.role==='student') } setLoading(false) })()},[id])
  async function enquire(){ const {data:{user}} = await supabase.auth.getUser(); if(!user){location.href='/auth'; return} if(!listing)return; const {error} = await supabase.from('enquiries').insert({listing_id:listing.id, student_id:user.id, message:`Interested in a free demo for ${listing.title}.`}); if(listing.phone){ const msg=encodeURIComponent(`Hi ${listing.title}, I found your class on TuitionSetu and I'm interested in a free demo.`); window.open(`https://wa.me/91${listing.phone.replace(/\D/g,'')}?text=${msg}`,'_blank') } setNote(error?error.message:(listing.phone?'Opening WhatsApp to connect you directly…':`Enquiry sent to ${listing.title}. They will contact you soon.`)) }
  async function submitReview(){ const {data:{user}} = await supabase.auth.getUser(); if(!user){location.href='/auth'; return} if(myRating<1){ setNote('Please select a star rating first.'); return } const {error} = await supabase.from('reviews').upsert({listing_id:id, student_id:user.id, rating:myRating, comment:comment||null},{onConflict:'listing_id,student_id'}); setNote(error?error.message:'Thanks! Your review has been posted.'); if(!error){ setComment(''); setMyRating(0); await loadReviews(); const {data} = await supabase.from('tutor_listings').select('*').eq('id',id).single(); setListing(data as Listing) } }
  if(loading) return <main className="tutor-page"><div className="skeleton tutor-cover"/><div className="tutor-body"><div className="skeleton tutor-skel-line"/><div className="skeleton tutor-skel-line short"/></div></main>
  if(!listing) return <main className="tutor-page"><div className="tutor-body"><h1>This listing isn't available.</h1><a className="primary inline" href="/student">Back to search</a></div></main>
  return <main className="tutor-page"><div className="tutor-cover">{listing.photo_url ? <img src={listing.photo_url} alt={listing.title} className="cover-img" /> : listing.category.slice(0,1)}</div><div className="tutor-body"><span className="verified">✓ VERIFIED</span><h1>{listing.title}</h1><p className="tutor-meta">{listing.category} · {listing.locality ? `${listing.locality}, ` : ''}{listing.city}</p>{listing.rating>0 && <p className="tutor-rating">★ {listing.rating.toFixed(1)} ({listing.review_count} reviews)</p>}<p className="tutor-desc">{listing.description || 'This tutor has not added a description yet.'}</p><div className="tutor-tags">{listing.modes.map(m=><span key={m} className="tag">{m}</span>)}</div><div className="tutor-cta"><b>{listing.fee_from ? `From ₹${listing.fee_from}${listing.fee_to?` – ₹${listing.fee_to}`:''}/month` : 'Fees on enquiry'}</b><button className="primary" onClick={enquire}>{listing.phone ? 'Chat on WhatsApp →' : 'Get free demo →'}</button></div>{note && <p className="notice">{note}</p>}<div className="review-form"><h2>Reviews</h2>{reviews.length===0 && <p className="subtle">No reviews yet. Be the first to share your experience.</p>}<div className="review-list">{reviews.map(r=><div className="review-item" key={r.id}><p className="review-stars">{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</p><p>{r.comment || 'No comment added.'}</p></div>)}</div>{isStudent && <div style={{marginTop:20}}><h3>Leave a review</h3><div className="stars">{[1,2,3,4,5].map(n=><button type="button" key={n} className={`star-btn ${n<=myRating?'filled':''}`} onClick={()=>setMyRating(n)}>★</button>)}</div><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="How was your experience with this tutor?" /><button className="primary" onClick={submitReview}>Post review</button></div>}</div></div></main>
}
