'use client'
import { FormEvent, useState } from 'react'
import { supabase } from '../../lib/supabase'
import type { Role } from '../../lib/types'

export default function AuthPage() {
  const [mode, setMode] = useState<'email'|'otp'>('email'); const [action, setAction] = useState<'login'|'signup'|'forgot'|'verify'>('signup'); const [role, setRole] = useState<Role>('student'); const [message, setMessage] = useState(''); const [phone, setPhone] = useState(''); const [otp, setOtp] = useState(''); const [sent, setSent] = useState(false); const [pendingEmail, setPendingEmail] = useState('')
  async function emailAuth(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const email = String(f.get('email')); const password = String(f.get('password')); setMessage(''); const result = action === 'signup' ? await supabase.auth.signUp({ email, password, options: { data: { role, full_name: String(f.get('name')) } } }) : await supabase.auth.signInWithPassword({ email, password }); if(action==='signup' && !result.error && (result as any).data?.user?.identities?.length===0){ setMessage('This email is already registered. Please log in instead.'); setAction('login'); return } const loggedIn = !result.error && (result as any).data?.session; if(!result.error && action==='signup' && !loggedIn){ setPendingEmail(email); setAction('verify'); setMessage('We sent a 6-digit code to your email. Enter it below to verify your account.'); return } setMessage(result.error ? result.error.message : loggedIn ? 'Account created. Opening your dashboard…' : 'Logged in. Opening your dashboard…'); if (!result.error && (action === 'login' || loggedIn)) location.href = '/dashboard' }
  async function verifySignupOtp(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const token = String(f.get('code')); setMessage(''); const result = await supabase.auth.verifyOtp({ email: pendingEmail, token, type: 'signup' }); setMessage(result.error ? result.error.message : 'Verified! Opening your dashboard…'); if(!result.error) location.href = '/dashboard' }
  async function forgotPassword(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const email = String(f.get('email')); setMessage(''); const result = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${location.origin}/auth/reset-password` }); setMessage(result.error ? result.error.message : 'Reset link sent. Please check your email.') }
  async function sendOtp(e: FormEvent) { e.preventDefault(); const result = await supabase.auth.signInWithOtp({ phone, options: { data: { role } } }); setMessage(result.error ? result.error.message : 'OTP sent to your mobile number.'); setSent(!result.error) }
  async function verifyOtp(e: FormEvent) { e.preventDefault(); const result = await supabase.auth.verifyOtp({ phone, token: otp, type: 'sms' }); setMessage(result.error ? result.error.message : 'Mobile verified. Opening your dashboard…'); if (!result.error) location.href = '/dashboard' }
  if (action === 'verify') return <main className="auth-shell"><section className="auth-card"><p className="eyebrow">VERIFY YOUR EMAIL</p><h1>Enter the code we sent you</h1><p className="subtle">We sent a 6-digit verification code to {pendingEmail}. Check your inbox (and spam folder).</p><form onSubmit={verifySignupOtp}><input required name="code" maxLength={6} placeholder="Enter 6-digit code" /><button className="primary">Verify & continue</button></form><button className="link-btn" onClick={async()=>{ const {error}=await supabase.auth.resend({type:'signup',email:pendingEmail}); setMessage(error?error.message:'A new code has been sent to your email.') }}>Resend code</button><button className="link-btn" onClick={()=>setAction('signup')}>Back to signup</button>{message && <p className="notice">{message}</p>}</section></main>
