'use client'
import { FormEvent, useState } from 'react'
import { supabase } from '../../lib/supabase'
import type { Role } from '../../lib/types'

export default function AuthPage() {
  const [mode, setMode] = useState<'email'|'otp'>('email'); const [action, setAction] = useState<'login'|'signup'|'forgot'|'verify'>('signup'); const [role, setRole] = useState<Role>('student'); const [message, setMessage] = useState(''); const [phone, setPhone] = useState(''); const [otp, setOtp] = useState(''); const [sent, setSent] = useState(false); const [pendingEmail, setPendingEmail] = useState('')
  async function emailAuth(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const email = String(f.get('email')); const password = String(f.get('password')); setMessage(''); const result = action === 'signup' ? await supabase.auth.signUp({ email, password, options: { data: { role, full_name: String(f.get('name')) } } }) : await supabase.auth.signInWithPassword({ email, password }); if(action==='signup' && !result.error && (result as any).data?.user?.identities?.length===0){ setMessage('This email is already registered. Please log in instead.'); setAction('login'); return } const loggedIn = !result.error && (result as any).data?.session; if(!result.error && action==='signup' && !loggedIn){ setPendingEmail(email); setAction('verify'); setMessage('We sent a 6-digit code to your email. Enter it below to verify your account.'); return } setMessage(result.error ? result.error.message : loggedIn ? 'Account created. Opening your dashboard…' : 'Logged in. Opening your dashboard…'); if (!result.error && (action === 'login' || loggedIn)) location.href = '/dashboard' }
  async function verifySignupOtp(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const token = String(f.get('code')); setMessage(''); const result = await supabase.auth.verifyOtp({ email: pendingEmail, token, type: 'signup' }); setMessage(result.error ? result.error.message : 'Verified! Opening your dashboard…'); if(!result.error) location.href = '/dashboard' }
  async function forgotPassword(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const email = String(f.get('email')); setMessage(''); const result = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${location.origin}/auth/reset-password` }); setMessage(result.error ? result.error.message : 'Reset link sent. Please check your email.') }
  async function sendOtp(e: FormEvent) { e.preventDefault(); const result = await supabase.auth.signInWithOtp({ phone, options: { data: { role } } }); setMessage(result.error ? result.error.message : 'OTP sent to your mobile number.'); setSent(!result.error) }
  async function verifyOtp(e: FormEvent) { e.preventDefault(); const result = await supabase.auth.verifyOtp({ phone, token: otp, type: 'sms' }); setMessage(result.error ? result.error.message : 'Mobile verified. Opening your dashboard…'); if (!result.error) location.href = '/dashboard' }
  if (action === 'verify') return <main className="auth-shell"><section className="auth-card"><p className="eyebrow">VERIFY YOUR EMAIL</p><h1>Enter the code we sent you</h1><p className="subtle">We sent a 6-digit verification code to {pendingEmail}. Check your inbox (and spam folder).</p><form onSubmit={verifySignupOtp}><input required name="code" maxLength={6} placeholder="Enter 6-digit code" /><button className="primary">Verify & continue</button></form><button className="link-btn" onClick={()=>setAction('signup')}>Back to signup</button>{message && <p className="notice">{message}</p>}</section></main>
  if (action === 'forgot') return <main className="auth-shell"><section className="auth-card"><p className="eyebrow">RESET PASSWORD</p><h1>Forgot your password?</h1><p className="subtle">Enter your email and we'll send you a reset link.</p><form onSubmit={forgotPassword}><input required name="email" type="email" placeholder="Email address" /><button className="primary">Send reset link</button></form><button className="link-btn" onClick={()=>setAction('login')}>Back to log in</button>{message && <p className="notice">{message}</p>}</section></main>
  return <main className="auth-shell"><section className="auth-card"><p className="eyebrow">WELCOME TO TUITIONSETU</p><h1>{action === 'signup' ? 'Create your account' : 'Welcome back'}</h1><p className="subtle">Choose how you would like to continue.</p><div className="tabs"><button className={mode==='email'?'selected':''} onClick={()=>setMode('email')}>Email & password</button><button className={mode==='otp'?'selected':''} onClick={()=>setMode('otp')}>Mobile OTP</button></div>{action === 'signup' && <div className="roles"><button className={role==='student'?'selected':''} onClick={()=>setRole('student')}>Student / Parent</button><button className={role==='tutor'?'selected':''} onClick={()=>setRole('tutor')}>Tutor / Institute</button></div>}{mode === 'email' ? <form onSubmit={emailAuth}>{action==='signup' && <input required name="name" placeholder="Your full name" />}<input required name="email" type="email" placeholder="Email address" /><input required name="password" type="password" minLength={8} placeholder="Password (at least 8 characters)" /><button className="primary">{action==='signup' ? 'Create account' : 'Log in'}</button></form> : !sent ? <form onSubmit={sendOtp}><input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Mobile with country code, e.g. +9198..." /><button className="primary">Send OTP</button></form> : <form onSubmit={verifyOtp}><input required value={otp} onChange={e=>setOtp(e.target.value)} placeholder="Enter the 6-digit OTP" /><button className="primary">Verify & continue</button></form>}<button className="link-btn" onClick={()=>setAction(action==='signup'?'login':'signup')}>{action==='signup' ? 'Already have an account? Log in' : 'New here? Create an account'}</button>{action==='login' && mode==='email' && <button className="link-btn" onClick={()=>setAction('forgot')}>Forgot password?</button>}{message && <p className="notice">{message}</p>}</section></main>
}
