'use client'
import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'

export default function Home() {
  const [stats,setStats]=useState({classes:0,enquiries:0,cities:0})
  useEffect(()=>{(async()=>{ const [{count:classes},{count:enquiries},{data:cityRows}] = await Promise.all([ supabase.from('tutor_listings').select('*',{count:'exact',head:true}).eq('status','active'), supabase.from('enquiries').select('*',{count:'exact',head:true}), supabase.from('tutor_listings').select('city').eq('status','active') ]); const cities = new Set((cityRows||[]).map((r:any)=>r.city)).size; setStats({classes:classes||0,enquiries:enquiries||0,cities}) })()},[])
  return <main><section className="home"><p className="eyebrow">LOCAL LEARNING, MADE SIMPLE</p><h1>The right class.<br />The right <em>future.</em></h1><p className="intro">TuitionSetu helps families find trusted local classes—and helps excellent tutors get discovered.</p><div className="choice"><a href="/student"><i>⌕</i><b>I'm a student or parent</b><small>Search verified tutors and coaching classes near you.</small><strong>Find a class →</strong></a><a href="/tutor/new"><i>✦</i><b>I'm a tutor or institute</b><small>Create a profile and receive genuine student enquiries.</small><strong>List my classes →</strong></a></div></section><section className="trust-strip"><div><b>{stats.classes}+</b><span>Verified classes</span></div><div><b>{stats.enquiries}+</b><span>Demo requests sent</span></div><div><b>{stats.cities}+</b><span>Cities covered</span></div></section><section className="three"><article><b>1</b><h3>Search or list</h3><p>Students browse local classes; tutors add their teaching profile.</p></article><article><b>2</b><h3>Compare clearly</h3><p>See relevant details like fees, batches, location and verification.</p></article><article><b>3</b><h3>Connect directly</h3><p>Request a demo and decide with confidence.</p></article></section></main>
}
