'use client'
import { FormEvent, useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import { supabase } from '../../../../lib/supabase'
import { CITIES } from '../../../../lib/cities'
import type { Listing } from '../../../../lib/types'

export default function EditListingPage(){
  const params = useParams(); const id = params?.id as string
  const [listing,setListing]=useState<Listing|null>(null); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(true)
  useEffect(()=>{(async()=>{ const {data:{user}}=await supabase.auth.getUser(); if(!user){location.href='/auth'; return} const {data}=await supabase.from('tutor_listings').select('*').eq('id',id).eq('owner_id',user.id).single(); setListing(data as Listing); setLoading(false) })()},[id])
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f=new FormData(e.currentTarget); let photo_url=listing?.photo_url||null; const file=f.get('photo') as File; if(file && file.size>0){ const {data:{user}}=await supabase.auth.getUser(); if(user){ const path=`${user.id}/${Date.now()}-${file.name}`; const {error:upErr}=await supabase.storage.from('listing-photos').upload(path,file); if(!upErr){ const {data:pub}=supabase.storage.from('listing-photos').getPublicUrl(path); photo_url=pub.publicUrl } } } const row={ title:String(f.get('title')),category:String(f.get('category')),city:String(f.get('city')),locality:String(f.get('locality'))||null,fee_from:Number(f.get('fee_from'))||null,fee_to:Number(f.get('fee_to'))||null,modes:[String(f.get('mode'))],description:String(f.get('description')),photo_url,phone:String(f.get('phone'))||null }; const {error}=await supabase.from('tutor_listings').update(row).eq('id',id); if(!error){ location.href=`/tutor/${id}` } else { setMessage(error.message) } }
  if(loading) return <main className="form-page">Loading your listing…</main>
  if(!listing) return <main className="form-page"><h1>Listing not found.</h1><a className="primary inline" href="/dashboard">Back to dashboard</a></main>
  return <main className="form-page"><div className="form-copy"><p className="eyebrow">EDIT LISTING</p><h1>Update your teaching profile.</h1><p>Changes go live immediately.</p></div><form className="form-card" onSubmit={submit}><p className="eyebrow">EDIT LISTING</p><h2>Your teaching profile</h2><label>Institute or tutor name<input required name="title" defaultValue={listing.title} /></label><div className="two"><label>City<input required name="city" defaultValue={listing.city} list="india-cities-edit" /></label><label>Locality<input name="locality" defaultValue={listing.locality||''} /></label></div><datalist id="india-cities-edit">{CITIES.map(c=><option key={c} value={c} />)}</datalist><label>WhatsApp number (10 digits, no +91)<input name="phone" type="tel" pattern="[0-9]{10}" defaultValue={listing.phone||''} /></label><label>Primary category<select required name="category" defaultValue={listing.category}><option value="">Choose a category</option><option>School tuition</option><option>Competitive exams</option><option>Languages</option><option>Computer & skills</option></select></label><div className="two"><label>Fees from (monthly)<input name="fee_from" type="number" min="0" defaultValue={listing.fee_from||''} /></label><label>Fees to (monthly)<input name="fee_to" type="number" min="0" defaultValue={listing.fee_to||''} /></label></div><label>Teaching mode<select name="mode" defaultValue={listing.modes[0]}><option>At institute</option><option>Home tuition</option><option>Online</option><option>Hybrid</option></select></label><label>Cover photo (leave empty to keep current)<input name="photo" type="file" accept="image/*" /></label><label>Short description<textarea name="description" required defaultValue={listing.description||''} /></label><button className="primary">Save changes</button>{message&&<p className="notice">{message}</p>}</form></main>
}
